# Generated by Django 3.0.3 on 2020-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pos_x',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='pos_y',
            field=models.IntegerField(default=None),
        ),
    ]
