# Generated by Django 3.0.3 on 2020-03-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200303_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pos_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='pos_y',
            field=models.IntegerField(default=0),
        ),
    ]
