# Generated by Django 3.0.3 on 2020-03-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200303_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomid',
            field=models.IntegerField(default=0),
        ),
    ]
