# Generated by Django 3.0.3 on 2020-03-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200303_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.IntegerField(default=0),
        ),
    ]
